server.port=8080
spring.application.name=users
spring.datasource.url=jdbc:mysql://localhost:3306/users
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=gRw100HDRas900/MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.datasource-platform=org.hibernate.dialect.MySQL8Dialect
